version: "3.8"
services:
    aws:
        build:
            dockerfile: ./Dockerfile
        container_name: "AWS_CONTAINER"
        ports:
            - "80:80"
            - "443:443"
        networks:
            - NETWORK
        volumes:
            - nginx-letsencrypt:/etc/letsencrypt
networks:
    NETWORK:
        name: NETWORK
        external: true
volumes:
    nginx-letsencrypt:
        name: nginx-letsencrypt
        labels:
            - dont-delete
